#!/bin/sh
# prerm script for bunsen-images-base

# Summary of ways this script is called:
#    prerm remove
#    old-prerm upgrade new-version
#    new-prerm failed-upgrade old-version
#    conflictor's-prerm remove in-favour package new-version
#    deconfigured's-prerm deconfigure in-favour package-being-installed version removing conflicting-package version

set -e

BL_GRUB_BACKGROUND='/boot/grub/images/bunsen/default.png'

BL_OTHER_GRUB_BACKGROUNDS='/boot/grub/images/bunsen/bark.png
/boot/grub/images/bunsen/sage.png'

case $1 in
remove|deconfigure|upgrade)
    if update-alternatives --list desktop-grub >/dev/null 2>&1
    then
        if [ -f "$BL_GRUB_BACKGROUND" ]
        then
            update-alternatives --remove desktop-grub "$BL_GRUB_BACKGROUND"
        fi
        while read -r image; do
            if [ -f "$image" ]
            then
                update-alternatives --remove desktop-grub "$image"
            fi
        done << EOF
$BL_OTHER_GRUB_BACKGROUNDS
EOF
        if command -v update-grub > /dev/null ; then
            sync
            update-grub || true
        fi
    fi
    ;;
esac

#DEBHELPER#

exit 0
