#!/bin/sh
# preinst script for bunsen-images-base

# Summary of ways this script is called:
#    new-preinst install
#    new-preinst install old-version (some config files remain from a previous install)
#    new-preinst upgrade old-version
#    old-preinst abort-upgrade new-version

set -e

BL_OLD_GRUB_BACKGROUNDS='/usr/share/backgrounds/bunsen/bunsen-images/bl-default/bl-grub.png
/usr/share/images/bunsen/grub/default.png
/boot/grub/images/bunsen/lithium.png'

# bl-login-background now dropped
if update-alternatives --list bl-login-background >/dev/null 2>&1
then
    update-alternatives --remove-all bl-login-background
fi

if altlist=$(update-alternatives --list desktop-grub 2>/dev/null)
then
    while read -r image
    do
        case "$altlist" in
        *"$image"*) update-alternatives --remove desktop-grub "$image";;
        *)  ;;
        esac
    done << EOF
$BL_OLD_GRUB_BACKGROUNDS
EOF
fi

#DEBHELPER#

exit 0
