#!/bin/sh
# postinst script for bunsen-images-base

# Summary of ways this script is called:
#    postinst configure most-recently-configured-version(null if not upgrade)
#    old-postinst abort-upgrade new-version
#    conflictor's-postinst abort-remove in-favour package new-version
#    deconfigured's-postinst abort-deconfigure in-favour failed-install-package version removing conflicting-package version

set -e

# default.png is a symlink to one of the images below
BL_GRUB_BACKGROUND='/boot/grub/images/bunsen/default.png'

# these will be added with priority 40
BL_OTHER_GRUB_BACKGROUNDS='/boot/grub/images/bunsen/bark.png
/boot/grub/images/bunsen/sage.png'

DESKTOP_BASE_DIR='/usr/share/images/desktop-base'
GRUB_ALT_LINK="$DESKTOP_BASE_DIR/desktop-grub.png"

case $1 in
configure)
    mkdir -p "$DESKTOP_BASE_DIR"
    if [ -f "$BL_GRUB_BACKGROUND" ] || [ -h "$BL_GRUB_BACKGROUND" ]
    then
        if ! update-alternatives --list desktop-grub | grep -q "$BL_GRUB_BACKGROUND"
        then
            update-alternatives --install "$GRUB_ALT_LINK" desktop-grub "$BL_GRUB_BACKGROUND" 50
        fi
        update-alternatives --set desktop-grub "$BL_GRUB_BACKGROUND"
    fi
    while read -r image; do
        if [ -f "$image" ] || [ -h "$image" ]
        then
            if ! update-alternatives --list desktop-grub | grep -q "$image"
            then
                update-alternatives --install "$GRUB_ALT_LINK" desktop-grub "$image" 40
            fi
        fi
    done << EOF
$BL_OTHER_GRUB_BACKGROUNDS
EOF
    if command -v update-grub > /dev/null ; then
        sync
        update-grub || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
