#!/bin/sh
# postrm script for bunsen-images-extra

set -e

GRUB_ALT_DIR='/usr/share/images/desktop-base'

case $1 in
remove|deconfigure)
    if ! dpkg -S "$GRUB_ALT_DIR" >/dev/null 2>&1 \
    && [ -d "$GRUB_ALT_DIR" ] \
    && [ -z "$(ls -A "$GRUB_ALT_DIR")" ] \
    && which rmdir >/dev/null
    then
        rmdir --ignore-fail-on-non-empty "$GRUB_ALT_DIR" || true
    fi
    ;;
esac

#DEBHELPER#

exit 0
